targets:
  $default:
    builders:
      artemis:
        options:
          scalar_mapping:
            - graphql_type: DateTime
              dart_type: DateTime
          schema_mapping:
            - output: lib/graphql/graphql_api.dart
              schema: lib/graphql/schema.gql
              queries_glob: lib/graphql/**/*.graphql
              fragments_glob: lib/fragments/**/*.graphql
